on:
  push:
    branches: [main, master]

name: Run experiments with Quarto and logolink

permissions: read-all

jobs:
  run-logolink:
    name: Run experiments
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    permissions:
      contents: write
      pages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # Install dependencies

          sudo apt-get update -qq

          sudo apt-get install -y -qq \
            libfontconfig1-dev \
            pandoc
        shell: bash

      - name: Set up NetLogo
        uses: danielvartan/logoactions/setup-netlogo@v1

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Check if renv is initialized
        id: renv-check
        run: |
          # Check if renv is initialized

          if [ -f "renv.lock" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Set up renv
        if: steps.renv-check.outputs.exists == 'true'
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 0
          bypass-cache: true

      - name: Install R dependencies
        if: steps.renv-check.outputs.exists == 'false'
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install logolink development version
        if: steps.renv-check.outputs.exists == 'false'
        run: |
          # Install logolink

          install.packages("remotes")

          remotes::install_github(
            repo = "danielvartan/logolink",
            auth_token = Sys.getenv("GH_TOKEN")
          )
        shell: Rscript {0}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto
        run: |
          # Render Quarto

          quarto render
        shell: bash

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
