on:
  push:
    branches: [main, master]

name: Run experiments with Quarto and logolink
permissions: read-all

jobs:
  run-logolink:
    name: Run experiments
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    permissions:
      contents: write
      pages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up NetLogo
        uses: danielvartan/logoactions/setup-netlogo@v1

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install system dependencies
        run: |
          # Install system dependencies

          sudo apt-get update -qq

          sudo apt-get install -y -qq \
            libfontconfig1-dev \
            pandoc
        shell: bash

      - name: Install R dependencies
        run: |
          # Install R dependencies

          install.packages(
            c(
              "rmarkdown",
              "knitr"
            )
          )
        shell: Rscript {0}

      - name: Check if renv is initialized
        id: renv-check
        run: |
          # Check if renv is initialized

          if [ -f "renv.lock" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        shell: bash
        working-directory: './tests/qmd'

      - name: Set up renv
        if: steps.renv-check.outputs.exists == 'true'
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: './tests/qmd'

      - name: Install and initialize renv
        if: steps.renv-check.outputs.exists == 'false'
        run: |
          # Install and initialize renv

          install.packages("renv")

          renv::init()
        shell: Rscript {0}
        working-directory: './tests/qmd'

      - name: Install logolink development version
        if: steps.renv-check.outputs.exists == 'false'
        run: |
          # Install logolink development version

          install.packages("remotes")

          remotes::install_github(
            repo = "danielvartan/logolink",
            auth_token = Sys.getenv("GH_TOKEN")
          )

          renv::snapshot()
        shell: Rscript {0}
        working-directory: './tests/qmd'

      - name: Render Quarto
        run: |
          # Render Quarto

          quarto render
        shell: bash
        working-directory: './tests/qmd'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: './tests/qmd/docs'
