on:
  push:
    branches: [main, master]

name: "setup-netlogo" # Do not change!

jobs:
  test-setup-netlogo:
    strategy:
      matrix:
        config:
          - {os: macos-latest, version: 'release'}
          - {os: windows-latest, version: '6.4.0'}
          - {os: windows-latest, version: 'release'}
          - {os: ubuntu-latest, version: '6.4.0'}
          - {os: ubuntu-latest, version: 'release'}
        cache: ['false', 'true']
    name: "${{matrix.config.os}} (version: '${{matrix.config.version}}') (cache: '${{matrix.cache}}')"
    runs-on: ${{matrix.config.os}}
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    permissions: read-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up NetLogo
        uses: ./setup-netlogo
        with:
          version: ${{matrix.config.version}}
          cache: ${{matrix.cache}}

      - name: Run experiment
        run: |
          # Run experiment
          if [[ "${NETLOGO_VERSION}" =~ ^[0-6]\. ]]; then
            model_ext="nlogo"
          else
            model_ext="nlogox"
          fi

          model_path="${NETLOGO_HOME}/models/Sample Models/Biology"
          model_file="Wolf Sheep Predation.${model_ext}"

          netlogo \
            --headless \
            --model "${model_path}/${model_file}" \
            --experiment "Wolf Sheep Crossing" \
            --table /tmp/table-output.csv

          cat /tmp/table-output.csv
        shell: bash
