on:
  push:
    branches: [main, master]

name: "check-netlogo" # Do not change!

jobs:
  test-check-netlogo:
    name: Check NetLogo models
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    permissions: read-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up NetLogo
        uses: danielvartan/netlogo-actions/setup-netlogo@v1

      - name: Check NetLogo models
        uses: ./check-netlogo
